<?= $this->headTitle('Create'); ?>



<h1 class="text-center my-5">Create Todos</h1>
    
    <div class="row justify-content-center">
        <div class="col-md-8">
           <div class="card card-default">
                <div class="card-header">Create New Todo</div>
                    
                <div class="card-body">
                <?php if($this->errors): ?>
                    <div class="alert alert-danger">
                        <ul class="list-group">
                            <?php foreach($this->errors as $error): ?>
                                <li class="list-group-item">
                                    <?= $error ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
                     <form action="/more/todos/store" method="POST">
                        
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Name" name="name" />
                        </div>
                            
                         <div class="form-group">
                            <textarea name="description" placeholder="Description" cols="5" rows="5" class="form-control"></textarea>
                        </div>
                            
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Create Todo</button>
                        </div>
                    </form>
                </div>
           </div>
        </div>
    </div>
    