<?= $this->headTitle('More Todos'); ?>

<h1 class="text-center my-5">TODOS Page</h1>
    
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-header">
                    Todos
                </div>
                 
                <div class="card-body">
                     <ul class="list-group">
                        <?php foreach($this->todos as $todo): ?>
                           
                           <li class="list-group-item">
                                <?php if(!$todo->getCompleted()): ?>
                                    <?= $this->escapeHtml($todo->getName()) ?>
                                <?php else: ?>
                                    <a href="<?= $this->url('show',['id' => $todo->getId()]); ?>"><?= $this->escapeHtml($todo->getName()) ?></a>
                                <?php endif; ?>
                               
                                <?php if(!$todo->getCompleted()): ?>
                                    <div class="float-right">
                                         <a href="/more/todos/<?= $this->escapeHtml($todo->getId()) ?>" class="btn btn-primary btn-sm">View</a>
                                         <a href="/more/todos/<?= $this->escapeHtml($todo->getId()) ?>/complete" class="btn btn-secondary btn-sm">Complete</a>
                                    </div>
                                <?php endif; ?>
                                
                           </li>
                           
                        <?php endforeach; ?>
                      </ul>
                </div>
           </div>
        </div>
    </div>