<?= $this->headTitle($todo->getName()); ?>

 <h1 class="text-center my-5">
            <?= $todo->getName() ?>
        </h1>
            
       <div class="row justify-content-center">
            <div class="col-md-6">
                 <div class="card card-default">
                    <div class="card-header">
                        Details         
                    </div>
                    
                    <div class="card-body">
                        <?= $todo->getDescription() ?>
                    </div>
                </div>
                <a href="/more/todos/<?= $todo->getId() ?>/edit" class="btn btn-info btn my-2">Edit</a>
                <a href="/more/todos/<?= $todo->getId() ?>/delete" class="btn btn-danger btn my-2">Delete</a>
            </div>
       </div>