<?= $this->headTitle('Edit'); ?>

  <h1 class="text-center my-5">Edit Todos</h1>
    
    <div class="row justify-content-center">
        <div class="col-md-8">
           <div class="card card-default">
                <div class="card-header">Edit Todo</div>
                    
                <div class="card-body">
                <?php if($errors): ?>
                    <div class="alert alert-danger">
                        <ul class="list-group">
                            <?php foreach($errors as $error): ?>
                                <li class="list-group-item">
                                    <?= $error ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
                     <form action="/todos/<?= $todo->getId() ?>/update" method="POST">
                        
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Name" name="name" value="<?= $todo->getName() ?>" />
                        </div>
                            
                         <div class="form-group">
                            <textarea name="description" placeholder="Description" cols="5" rows="5" class="form-control"><?= $todo->getDescription() ?></textarea>
                        </div>
                            
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Update Todo</button>
                        </div>
                    </form>
                </div>
           </div>
        </div>
    </div>