<?= $this->headTitle('Todos'); ?>

<h1 class="text-center my-5">TODOS Page</h1>
    
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card card-default">
                <div class="card-header">
                    Todos
                </div>
                 
                <div class="card-body">
                     <ul class="list-group">
                        <?php foreach($this->todos as $todo): ?>
                           
                           <li class="list-group-item">
                                <?php if(!$todo['completed']): ?>
                                    <?= $this->escapeHtml($todo['name']) ?>
                                <?php else: ?>
                                    <a href=<?= $this->url('show',['id' => $todo['id']]); ?>><?= $this->escapeHtml($todo['name']) ?></a>
                                <?php endif; ?>
                               
                                <?php if(!$todo['completed']): ?>
                                    <div class="float-right">
                                         <a href="/todos/<?= $this->escapeHtml($todo['id']) ?>" class="btn btn-primary btn-sm">View</a>
                                         <a href="/todos/<?= $this->escapeHtml($todo['id']) ?>/complete" class="btn btn-secondary btn-sm">Complete</a>
                                    </div>
                                <?php endif; ?>
                                
                           </li>
                           
                        <?php endforeach; ?>
                      </ul>
                </div>
           </div>
        </div>
    </div>