<?php

$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   ['alert fadeout', 'alert-dismissible', 'alert-danger']);
echo $flash->render('info',    ['alert fadeout', 'alert-dismissible', 'alert-info']);
echo $flash->render('default', ['alert fadeout', 'alert-dismissible', 'alert-warning']);
echo $flash->render('success', ['alert fadeout', 'alert-dismissible', 'alert-success']);
